routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\SettingsController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/file', [ImageController::class, 'uploadImages']);
Route::get('/get-events', [SettingsController::class, 'events']);
Route::post('/store-event', [SettingsController::class, 'storeEvent']);

// Backend routes go first, or it will be rewritten by wildcard
Route::get('/backend/login', [LoginController::class, 'show'])->name('login');
Route::post('/backend/login', [LoginController::class, 'authenticate'])->name('login-attempt');
Route::get('/backend/logout', [LoginController::class, 'logout'])->name('logout');


Route::get('/backend', [AdminController::class, 'index'])->name('admin.home');
Route::get('/backend/{any}', [AdminController::class, 'index'])->where('any', '.*');

// Openapi specification
Route::get('/openapi_spec', function () {
  return Storage::get('private/files/openapi.json');
});

// Sitemap.xml
Route::get('/sitemap.xml', function () {
    return (new SettingsController())->generateSitemap();
});

// Site pages
Route::get('/', [PageController::class, 'index']);
Route::get('/{section}/{page?}', [PageController::class, 'section'])->where([
  'section' => '[\w\-]+',
  'page'    => '[\w\-]+',
]);

app/Models/Coin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;


class Coin extends Model
{
    public const CONDITION_UNCIRCULATED             = 3;
    public const CONDITION_BRILLIANT_UNCIRCULATED   = 4;
    public const CONDITION_PROOF                    = 5;

    public const METAL_GOLD       = 1;
    public const METAL_PLATINUM   = 2;
    public const METAL_SILVER     = 3;

    public const CONDITIONS = [
        self::CONDITION_UNCIRCULATED            => 'UNC',
        self::CONDITION_BRILLIANT_UNCIRCULATED  => 'BU',
        self::CONDITION_PROOF                   => 'PROOF',
    ];

    public const METALS = [
        self::METAL_GOLD        => 'Золото',
        self::METAL_PLATINUM    => 'Платина',
        self::METAL_SILVER      => 'Серебро',
    ];

    /**
     * The relationships that should always be loaded.
     * @var array
     */
    protected $with = ['meta_tags', 'image_object'];


    /** @var string[] "Защищённые" от инъекций поля */
    protected $guarded = ['id'];

    /** @var string[] Типы умолчаний */
    protected $casts = [
        'weight'                => 'float',
        'weightPure'            => 'float',
        'metalId'               => 'integer',
        'purity'                => 'integer',
        'diameter'              => 'float',
        'thickness'             => 'float',
        'year'                  => 'integer',
        'periodFrom'            => 'integer',
        'periodTo'              => 'integer',
        'mintage'               => 'integer',
        'countryId'             => 'integer',
        'isActive'              => 'boolean',
        'conditionId'           => 'integer',
        'priceBuy'              => 'float',
        'priceSell'             => 'float',
        'nofMinDiscussPrice'    => 'float',
        'nofAvailable'          => 'integer',
        'order'                 => 'integer',
    ];

    /** @var string[] Дополнительные поля */
    protected $appends = [
        'images',
        'metal',
        'countryName',
        'condition',
    ];

    public function scopeActive($query)
    {
        return $query->where('isActive', true);
    }

  /**
   * Возвращает картинки для реверса и аверса,
   * если картинка отсутствует - возвращает заглушку
   *
   * @return string[]
   */
    public function getImagesAttribute(): array
    {
        $images = [];
        foreach ([1, 2] as $index) {
          $image = "/storage/coins/$this->id-$index";
          $file = "public/coins/$this->id-$index";
          if (Storage::exists("$file.png")) {
            $images[] = "$image.png";
          } elseif (Storage::exists("$file.jpg")) {
            $images[] = "$image.jpg";
          } else {
            $images[] = '//via.placeholder.com/232x232';
          }
        }

        return $images;
    }


    /**
     * Возвращает название металла по заданному ID
     *
     * @return string[]
     */
    public function getMetalAttribute(): array
    {
        $metals = [];

        foreach (self::METALS as $id => $name) {
            $metals[] = [
                'id'    => $id,
                'name'  => $name,
            ];
        }

        $metals = collect($metals);

        return $metals->where('id', $this->getAttribute('metalId'))->first() ?? $metals[0];
    }

    /**
     * Возвращает название состояния по заданному ID
     *
     * @return string[]
     */
    public function getConditionAttribute(): array
    {
        $conditions = [];

        foreach (self::CONDITIONS as $id => $name) {
            $conditions[] = [
                'id'    => $id,
                'name'  => $name,
            ];
        }

        $conditions = collect($conditions);

        return $conditions->where('id', $this->getAttribute('conditionId'))->first() ?? $conditions[0];
    }

    public function getCountryNameAttribute()
    {
        return $this->getAttribute('country')->name;
    }

    /**
     * Get the country that owns the coin.
     *
     * @return BelongsTo
     */
    public function country(): BelongsTo
    {
        return $this->belongsTo(Country::class, 'countryId');
    }

    public function getTypeAttribute()
    {
        return 'coin';
    }

    /**
     * Get the coin's meta tags.
     */
    public function meta_tags()
    {
        return $this->morphMany(MetaTag::class, 'metatagable');
    }

    public function getOgTitleAttribute()
    {
        $tag = $this->getAttribute('meta_tags');
        if ($tag) {
            $tag = $tag->where('name', 'ogTitle')->first();
        }
        return $tag ? $tag->value : null;
    }

    public function getOgDescriptionAttribute()
    {
        $tag = $this->getAttribute('meta_tags');
        if ($tag) {
            $tag = $tag->where('name', 'ogDescription')->first();
        }
        return $tag ? $tag->value : null;
    }

    public function getOgImageAttribute()
    {
        $tag = $this->getAttribute('meta_tags');
        if ($tag) {
            $tag = $tag->where('name', 'ogImage')->first();
        }
        return $tag ? $tag->value : null;
    }

    public function getOgImageWidthAttribute()
    {
        $tag = $this->getAttribute('meta_tags');
        if ($tag) {
            $tag = $tag->where('name', 'ogImageWidth')->first();
        }
        return $tag ? $tag->value : null;
    }

    public function getOgImageHeightAttribute()
    {
        $tag = $this->getAttribute('meta_tags');
        if ($tag) {
            $tag = $tag->where('name', 'ogImageHeight')->first();
        }
        return $tag ? $tag->value : null;
    }

    /**
     * Get the coin's image.
     */
    public function image_object()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    public function getImageAltAttribute()
    {
        $imageObject = $this->getAttribute('image_object');
        $imageObject1 = $imageObject->where('name', 'alt_1')->first();
        $imageObject2 = $imageObject->where('name', 'alt_2')->first();
        return [
          1 => $imageObject1 ? $imageObject1->value : '',
          2 => $imageObject2 ? $imageObject2->value : '',
        ];
    }
}

resources/views/pages/home.blade.php
@extends('layouts.index')

@section('meta')
    @component('layouts.meta')
        @slot('page', $pages[0]->load('meta_tags'))
    @endcomponent
@endsection

@section('content')
    <div class="page home__page">
        <banners :banners="{{ json_encode($banners, true) }}"></banners>
        <div class="container">
            <div class="coins row">
                @foreach($coins['coins'] as $coin)
                    <div class="col-6 col-lg-4 col-xl-3 coin__wrap align-items-stretch">
                        <coin :coin="{{ json_encode($coin, true) }}"></coin>
                    </div>
                @endforeach
            </div>
            <div class="news row mt-5">
                <div class="col-12 d-flex align-items-end justify-content-between news__header mb-4">
                    <h3 class="mb-0">{{ $pages[2]->json_body['title'] }}</h3>
                    <a class="text-brand-color font-weight-bold" href="{{ $pages[2]->slug }}">Все новости</a>
                </div>
                @foreach($articles['news'] as $article)
                    <div class="col-12 col-md-4 article__wrap mb-4 mb-lg-0">
                        <news-article :article="{{ $article }}"></news-article>
                    </div>
                @endforeach
            </div>
            <div class="position-relative">
                <div id="questions" class="questions-label position-absolute"></div>
            </div>
            <faq
                    :title="{{ json_encode($pages[3]->json_body['title'], true) }}"
                    :questions="{{ json_encode($pages[3]->json_body['questions'], true) }}"
            ></faq>
        </div>
    </div>
@endsection

resources/views/pages/page.blade.php
@extends('layouts.index')

@section('meta')
    @component('layouts.meta')
        @slot('page', $subPage ?? $page)
    @endcomponent
@endsection

@section('content')
    @if(!$subPage)
        @includeIf('pages.components.' . $page->id)
    @else
        @includeIf('pages.components.' . $subPage->type)
    @endif
@endsection